# ========================================
# RAG config
# ========================================
rag_implementation_name: naiverag

# ----------------------------------------
# API
# ----------------------------------------

api_implementation_name: "gemini"
api_key: ${API_KEY}
llm_model_name: "gemini-2.0-flash"
embedding_model_name: "text-embedding-004"

# ----------------------------------------
# Chunking
# ----------------------------------------

chunking_implementation_name: "token_size"
overlap_token_size: 50
max_token_size: 1000
tokenizer: "cl100k_base"  # fallback tokenizer (e.g. GPT-4o) for unsupported models

# ----------------------------------------
# DB
# ----------------------------------------

db_implementation_name: "nano_vdb"
embedding_dim: 768
dir_doc_store: "./doc_store"
dir_text_chunks: "./vector_store/text_chunks/"
dir_vector_db: "./vector_store/vector_db/"
